### ISSUE TITLE
Seeing timeouts for good responses

### ISSUE THREAD

**Issue by byrnedo** [repejota/phpnats#103]
I just updated to 0.8.4 and started seeing that the callback hangs during the socket read, not sure if it's just my local or something else? 
Has anyone seen anything like this?

Is it anything to do with the `wait(2)` in the request function? The signature used to have `$wait=1` as the default before (`public function request($subject, $payload, $callback, $wait = 1)`)
```

    public function request($subject, $payload, \Closure $callback)
    {
        $inbox = uniqid('_INBOX.');
        $this->subscribe(
            $inbox,
            $callback
        );
        $msg = 'PUB '.$subject.' '.$inbox.' '.strlen($payload);
        $this->send($msg."\r\n".$payload);
        $this->pubs += 1;
        $this->wait(2);
    }
```

I see that it's commit 4115fdd9211404ac598171b63648825681b186cc that changed this

**Comment by repejota** [comment]
Taking a look!

**Comment by byrnedo** [comment]
Thanks!

**Comment by repejota** [comment]
Fixed in https://github.com/repejota/phpnats/releases/tag/0.8.5
