### ISSUE TITLE
getStream has incorrect args and echoes on failure

### ISSUE THREAD

**Issue by nickcarenza** [repejota/phpnats#24]
http://php.net/manual/en/function.stream-socket-client.php

`STREAM_CLIENT_CONNECT` is used where the $timeout argument goes. It evaultes to `4` so the timeout is set to 4.

Also on failure, the method actually echoes instead of returning an error to be handled.

Can we remove the echo and allow for a configurable timeout please?

**Comment by repejota** [comment]
Hi Nick!
Gonna take a look and return back to you ASAP. Thanks for that suggestion! :muscle:

**Comment by nickcarenza** [comment]
Hi, thanks for the response. I have addressed these in a fork if you are interested in checking it out.

https://github.com/the-control-group/phpnats/tree/0.0.8

**Comment by repejota** [comment]
Yup mate, took your changes and applied to my code adding proper docs and docstrings.
So fixed! 

Thanks! :smile:
