### ISSUE TITLE
Add queue support for phpnats

### ISSUE THREAD

**Issue by repejota** [repejota/phpnats#38]
Currently phpnats supports Pub/Sub & Request/Response patterns to interact with NATs server.

Implement queue support according the docs here:
http://nats.io/documentation/concepts/nats-queueing/

**Comment by adriacidre** [comment]
Nats protocol documentation:

## SUB
#### Syntax
```
SUB <subject> [queue group] <sid>\r\n
```

#### Where:
- subject: The subject name to subscribe to
- queue group: If specified, the subscriber will join this queue group
- sid: A unique alphanumeric subscription ID

#### Description
SUB initiates a subscription to a subject, optionally joining a distributed queue group.

#### Example
To subscribe to the subject FOO with the connection-unique subject identifier (sid) 1:
```
SUB FOO 1\r\n
```
To subscribe the current connection to the subject BAR as part of distribution queue group G1 with sid 44:
```
SUB BAR G1 44\r\n
```

Protocol docs: http://nats.io/documentation/internals/nats-protocol/

**Comment by repejota** [comment]
@adriacidre :muscle: !!! Thanks for the complementary info.
