### ISSUE TITLE
Unauthorised connection doesn't trigger an error.

### ISSUE THREAD

**Issue by repejota** [repejota/phpnats#4]
If I start the server with user and password like this:

```
gnatsd -D -V --user foo --pass bar
```

And I try to connect without user and password, the client does not tigger an error.

**Comment by deviantmk** [comment]
any update on this?

**Comment by repejota** [comment]
Hi @deviantmk we've been busy stabilising our tests suite. 
But now that is working, I'm going to work on this ASAP. 

Thanks!

**Comment by josgilmo** [comment]
Hi @deviantmk, i have just sent a PR fixing the problem with the connection with user and password. If you can say if now works, I'll appreciate that.

@repejota, take a look you also, please.

**Comment by repejota** [comment]
Cool! I will UAT it as soon as I can. I guess this weekend for sure :+1: :smile_cat:

**Comment by deviantmk** [comment]
Thanks guys, that was quick :thumbsup:
