### ISSUE TITLE
Protobuffers

### ISSUE THREAD

**Issue by byrnedo** [repejota/phpnats#43]
Hi, is there a way to get this to work with protobuf?

**Comment by repejota** [comment]
Sure ... I will take a look and publish here my research. :muscle:

**Comment by byrnedo** [comment]
Hi @repejota, 

I did a bit of experimenting myself using https://github.com/skrz/meta and I can seem to send messages, but the response bodies seem to get lost. 

When I send data as json it works fine, but when I switch to protobuf, only requests from php-nats work, reply bodies are empty.

**Comment by byrnedo** [comment]
Printing in the `receive` function I get the following:
```
INFO {"server_id":"ff331bd33f1fda7518cf2822ca9446b2","version":"0.7.2","go":"go1.5.2","host":"0.0.0.0","port":4222,"auth_required":false,"ssl_required":false,"tls_required":false,"tls_verify":false,"max_payload":1048576} 

PONG

MSG _INBOX.572747b760a34 572747b760a72 89
``` 

So that would indicate that the message I should be receiving is length 89 right?

**Comment by byrnedo** [comment]
https://github.com/repejota/phpnats/pull/46

Any pointers on how to best test this?
