### ISSUE TITLE
Call to a member function setStreamTimeout() on a non-object in Nats/Connection.php:454

### ISSUE THREAD

**Issue by byrnedo** [repejota/phpnats#74]
Connection::setStreamTimeout is broken :o

**Comment by byrnedo** [comment]
Made pull-request: #75

**Comment by byrnedo** [comment]
Would be awesome to get this in soon if you think it looks good :)

**Comment by dfeyer** [comment]
@repejota This one can be closed ? And did you plan a release ?

**Comment by repejota** [comment]
Closed and released phpNATS 0.8.0
