### ISSUE TITLE
Deprecated exception on PHP 7.1

### ISSUE THREAD

**Issue by byrnedo** [repejota/phpnats#88]
`Function mcrypt_module_open() is deprecated in /usr/share/nginx/vendor/ircmaxell/random-lib/lib/RandomLib/AbstractMcryptMixer.php:75`

I think that the fix might be to use `random_bytes()` in php 7+.

https://github.com/ircmaxell/RandomLib/issues/55

Edit: locally using something like the following works to guard via version:

```
if(version_compare(phpversion(), '7.0', '>')){
...
```

**Comment by byrnedo** [comment]
See https://github.com/repejota/phpnats/pull/89

**Comment by byrnedo** [comment]
@repejota Any plan to merge this soon? Are you still maintaining this project?

**Comment by repejota** [comment]
Sure, I'll take a look ASAP sorry really busy lately. Gonna be be merged tomorrow maximum.

Thanks!

**Comment by byrnedo** [comment]
No worries, just wanted to check. It's nothing that can't wait a bit.
